create table if not exists public.cong_trinh (
  id bigint generated by default as identity not null,
  created_at timestamp without time zone not null default now(),
  name_congtrinh character varying null,
  name_customer character varying null,
  sdt numeric null,
  email character varying null,
  "Id_sale" bigint null,
  ngan_sach_du_kien numeric null,
  mo_ta text null,
  status text null,
  dia_chi text null,
  constraint cong_trinh_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_cong_trinh_status on public.cong_trinh using btree (status) TABLESPACE pg_default;

create index IF not exists idx_cong_trinh_created_at on public.cong_trinh using btree (created_at) TABLESPACE pg_default;