-- Tạo bảng user_chat để lưu thông tin chat với email
CREATE TABLE IF NOT EXISTS public.user_chat (
  id bigint generated by default as identity not null,
  app_id text null,
  conversation_id text null,
  email text null,
  user_id bigint null,
  name_app text null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint user_chat_pkey primary key (id)
) TABLESPACE pg_default;

-- Tạo index cho performance
CREATE INDEX IF NOT EXISTS idx_user_chat_email ON public.user_chat(email);
CREATE INDEX IF NOT EXISTS idx_user_chat_user_id ON public.user_chat(user_id);
CREATE INDEX IF NOT EXISTS idx_user_chat_conversation_id ON public.user_chat(conversation_id);
