#!/usr/bin/env python3
"""
Script để tạo lại bảng loaichiphi với cấu trúc mới
"""
import sys
import os
sys.path.append(os.path.dirname(__file__))

from supabase_client import supabase

def recreate_loaichiphi_with_new_schema():
    """Tạo lại bảng loaichiphi với schema mới"""
    try:
        print("🚀 Bắt đầu tạo lại bảng loaichiphi với cấu trúc mới...")

        # Drop bảng cũ nếu tồn tại
        try:
            drop_sql = "DROP TABLE IF EXISTS loaichiphi CASCADE"
            supabase.rpc('exec_sql', {'sql': drop_sql})
            print("✅ Đã xóa bảng cũ")
        except Exception as e:
            print(f"⚠️  Không thể xóa bảng cũ: {str(e)}")

        # Tạo bảng mới với cấu trúc mới
        create_sql = '''
        CREATE TABLE public.loaichiphi (
          id bigint generated by default as identity not null,
          loaichiphi character varying null,
          tenchiphi character varying null,
          giathanh numeric null,
          constraint loaichiphi_pkey primary key (id)
        ) TABLESPACE pg_default;
        '''
        supabase.rpc('exec_sql', {'sql': create_sql})
        print("✅ Đã tạo bảng mới với cấu trúc mới")

        # Insert dữ liệu mẫu
        sample_data = [
            {
                'loaichiphi': 'biến phí',
                'tenchiphi': 'Chi phí nguyên vật liệu',
                'giathanh': None
            },
            {
                'loaichiphi': 'định phí',
                'tenchiphi': 'Chi phí nhân công',
                'giathanh': 5000000
            },
            {
                'loaichiphi': 'biến phí',
                'tenchiphi': 'Chi phí vận chuyển',
                'giathanh': None
            },
            {
                'loaichiphi': 'biến phí',
                'tenchiphi': 'Chi phí marketing',
                'giathanh': None
            },
            {
                'loaichiphi': 'định phí',
                'tenchiphi': 'Chi phí văn phòng',
                'giathanh': 2000000
            },
            {
                'loaichiphi': 'biến phí',
                'tenchiphi': 'Chi phí bảo trì',
                'giathanh': None
            },
            {
                'loaichiphi': 'định phí',
                'tenchiphi': 'Chi phí điện nước',
                'giathanh': 1500000
            },
            {
                'loaichiphi': 'định phí',
                'tenchiphi': 'Chi phí thuê mặt bằng',
                'giathanh': 10000000
            }
        ]

        # Insert từng record
        for item in sample_data:
            try:
                result = supabase.table('loaichiphi').insert(item).execute()
                print(f"✓ Đã tạo: {item['tenchiphi']} ({item['loaichiphi']})")
            except Exception as e:
                print(f"❌ Lỗi khi tạo {item['loaichiphi']}: {str(e)}")

        print(f"\n✅ Hoàn thành! Đã tạo {len(sample_data)} loại chi phí mẫu với cấu trúc mới.")

    except Exception as e:
        print(f"❌ Lỗi: {str(e)}")

if __name__ == "__main__":
    recreate_loaichiphi_with_new_schema()
