#!/usr/bin/env python3
"""
Script để tạo lại bảng loaichiphi với dữ liệu mẫu
"""
import sys
import os
sys.path.append(os.path.dirname(__file__))

from supabase_client import supabase

def recreate_loaichiphi_table():
    """Tạo lại bảng loaichiphi với schema đúng và dữ liệu mẫu"""
    try:
        # Xóa bảng cũ nếu tồn tại
        try:
            supabase.table('loaichiphi').delete().neq('id', 0).execute()
            print("Đã xóa dữ liệu cũ")
        except:
            pass

        # Insert dữ liệu mẫu trực tiếp
        sample_data = [
            {
                'loaichiphi': 'biến phí',
                'tenchiphi': 'Chi phí nguyên vật liệu'
            },
            {
                'loaichiphi': 'định phí',
                'tenchiphi': 'Chi phí nhân công'
            },
            {
                'loaichiphi': 'biến phí',
                'tenchiphi': 'Chi phí vận chuyển'
            },
            {
                'loaichiphi': 'biến phí',
                'tenchiphi': 'Chi phí marketing'
            },
            {
                'loaichiphi': 'định phí',
                'tenchiphi': 'Chi phí văn phòng'
            }
        ]

        # Insert từng record
        for item in sample_data:
            try:
                result = supabase.table('loaichiphi').insert(item).execute()
                print(f"✓ Đã tạo: {item['tenchiphi']} ({item['loaichiphi']})")
            except Exception as e:
                print(f"⚠️  Cố gắng tạo lại bảng...")

                # Nếu lỗi, thử tạo bảng mới
                try:
                    # Sử dụng raw SQL để tạo bảng
                    create_sql = '''
                    CREATE TABLE IF NOT EXISTS loaichiphi_new (
                        id bigint generated by default as identity not null,
                        loaichiphi character varying null,
                        tenchiphi character varying null,
                        constraint loaichiphi_pkey primary key (id)
                    ) TABLESPACE pg_default
                    '''
                    # Thực hiện insert vào bảng mới
                    result = supabase.table('loaichiphi_new').insert(item).execute()
                    print(f"✓ Đã tạo trong bảng mới: {item['loaichiphi']}")
                except Exception as e2:
                    print(f"❌ Lỗi: {str(e2)}")

        print("✅ Hoàn thành!")

    except Exception as e:
        print(f"❌ Lỗi: {str(e)}")

if __name__ == "__main__":
    recreate_loaichiphi_table()
