#!/usr/bin/env python3
"""
Script để tạo bảng user_chat
"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.supabase_client import supabase

def create_user_chat_table():
    """Tạo bảng user_chat trong database"""

    sql = """
    CREATE TABLE IF NOT EXISTS public.user_chat (
      id bigint generated by default as identity not null,
      app_id text null,
      conversation_id text null,
      email text null,
      user_id bigint null,
      name_app text null,
      created_at timestamp with time zone default timezone('utc'::text, now()) not null,
      constraint user_chat_pkey primary key (id)
    ) TABLESPACE pg_default;

    CREATE INDEX IF NOT EXISTS idx_user_chat_email ON public.user_chat(email);
    CREATE INDEX IF NOT EXISTS idx_user_chat_user_id ON public.user_chat(user_id);
    CREATE INDEX IF NOT EXISTS idx_user_chat_conversation_id ON public.user_chat(conversation_id);
    """

    try:
        print("Đang tạo bảng user_chat...")
        result = supabase.rpc('exec_sql', {'sql': sql})
        print("✓ Bảng user_chat đã được tạo thành công!")
    except Exception as e:
        print(f"⚠ Lỗi khi tạo bảng: {e}")
        # Thử chạy từng câu SQL riêng biệt
        sql_parts = [stmt.strip() for stmt in sql.split(';') if stmt.strip()]
        for i, stmt in enumerate(sql_parts):
            try:
                print(f"Thực thi phần {i+1}...")
                result = supabase.rpc('exec_sql', {'sql': stmt})
                print(f"✓ Phần {i+1} thành công")
            except Exception as e2:
                print(f"⚠ Phần {i+1} thất bại: {e2}")

if __name__ == "__main__":
    print("🚀 Creating user_chat table...")
    create_user_chat_table()
